### ISSUE TITLE
Album Artwork

### ISSUE THREAD

**Issue by itsmidnightyo** [ironsmile/httpms#22]
How hard would it be to implement adding the track/album art within the API? i think it would be a pretty cool feature.
as well as adding POST / PUT / DELETE features so you can edit your library from the frontend. 💯

**Comment by ironsmile** [comment]
I am [in the process](https://github.com/ironsmile/httpms/tree/album-artwork#album-artwork) of doing exactly that. But it is still WIP. My idea at them moment involves automatic detection of existing artwork. The album directories would be scanned for existing image files and the cover image would be identified if one is present. Failing that, one would be able to enable integration with Music Brainz' [Cover Art Archive](https://musicbrainz.org/doc/Cover_Art_Archive).

Managing the artwork via the API fits very well with this idea and would be supported as well. PUT and DELETE methods would be easy to implement so I will do it for sure.

**Comment by itsmidnightyo** [comment]
that sounds absolutely amazing, i love your work ethic on this. 👍 !
i was looking at this repository the other day ([soundcloud-redux](https://github.com/r-park/soundcloud-redux)) and i was thinking about how i could possibly modify the existing code with my own API. a while after, i came across httpms and i can't believe that nobody else is contributing to this. 💯 
i'm pretty new when it comes to react/user authentication and api's. i can't wait to see this project rise to the top of the charts.

**Comment by ironsmile** [comment]
This is done and is now in `master`. You can [see the README](https://github.com/ironsmile/httpms#album-artwork) for how to use it. At this point the artwork is not shown in the web interface because I have no idea where to put it and still keep the simple UI. But this will come later.
